version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: production
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production